config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'counter', to: 'counter#show'
  post 'increment', to: 'counter#increment'
  post 'decrement', to: 'counter#decrement'

  # Defines the root path route ("/")
  root 'articles#index'

  get '/articles', to: 'articles#index'
  get 'dashboard', to: 'dashboard#show'

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index; end
end

app/controllers/auth0_controller.rb
# frozen_string_literal: true

# ./app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # OmniAuth stores the information returned from Auth0 and the IdP in request.env['omniauth.auth'].
    # In this code, you will pull the raw_info supplied from the id_token and assign it to the session.
    # Refer to https://github.com/auth0/omniauth-auth0/blob/master/EXAMPLES.md#example-of-the-resulting-authentication-hash for complete information on 'omniauth.auth' contents.
    auth_info = request.env['omniauth.auth']
    session[:userinfo] = auth_info['extra']['raw_info']

    # Redirect to the URL you want after successful auth
    redirect_to '/dashboard'
  end

  def failure
    # Handles failed authentication -- Show a failure page (you can also handle with a redirect)
    @error_msg = request.params['message']
  end

  def logout
    reset_session
    redirect_to logout_url, allow_other_host: true
  end

  private

  def logout_url
    request_params = {
      returnTo: root_url,
      client_id: AUTH0_CONFIG['auth0_client_id']
    }

    URI::HTTPS.build(host: AUTH0_CONFIG['auth0_domain'], path: '/v2/logout', query: request_params.to_query).to_s
  end
end

app/controllers/concerns/secured.rb
# frozen_string_literal: true

# ./app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :logged_in_using_omniauth?
  end

  def logged_in_using_omniauth?
    redirect_to '/' unless session[:userinfo].present?
  end
end

app/controllers/counter_controller.rb
# frozen_string_literal: true

class CounterController < ApplicationController
  before_action :counter
  def show; end

  def increment
    counter.increment
    # stream_counter
    Turbo::StreamsChannel.broadcast_update_to('counter_stream', target: 'counter', html: counter.value)
  end

  def decrement
    counter.decrement
    # stream_counter
    Turbo::StreamsChannel.broadcast_update_to('counter_stream', target: 'counter', html: counter.value)
  end

  private

  def counter
    @counter ||= Kredis.counter 'mycounter'
  end

  def stream_counter
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update('counter', html: counter.value)
      end
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# ./app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Secured

  def show
    # session[:userinfo] was saved earlier on Auth0Controller#callback
    @user = session[:userinfo]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/counter_helper.rb
# frozen_string_literal: true

module CounterHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

<%= button_to 'Login', '/auth/auth0', method: :post, data: { turbo: false } %>
<%= button_to 'Logout', 'auth/logout', method: :get, data: { turbo: false } %>

app/views/counter/show.html.erb
<h1>Counter#show</h1>
<p>Find me in app/views/counter/show.html.erb</p>

<%= turbo_stream_from 'counter_stream' %>

<%= button_to '+', increment_path %>

<div id='counter' >
<%= @counter.value %>
</div>

<%= button_to '-', decrement_path %>

app/views/dashboard/show.html.erb
<!-- ./app/views/dashboard/show.html.erb -->
<div>
  <p>Normalized User Profile:<%= JSON.pretty_generate(@user)%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chess</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>